# Generated by Django 4.2.7 on 2023-12-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='542760081738', max_length=15, verbose_name='Проверочный код'),
        ),
    ]