# Generated by Django 4.2.7 on 2023-12-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_country_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='527159406650', max_length=15, verbose_name='Проверочный код'),
        ),
    ]