# Generated by Django 4.2.7 on 2023-12-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_blog_count_views_remove_blog_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
    ]