# Generated by Django 5.0.1 on 2024-02-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_publication', 'Can change status publication'), ('set_category', 'Can change category'), ('set_description', 'Can change description')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
